import time
print("Hello World")
time.sleep(2)
print("This Python Program is build to read Text Files which you have downloaded from Website")
time.sleep(5)
print("So please Read the Story of a Little Cowbow that Python is going to show You")
time.sleep(5)
f = open("Reading.txt", "r")
print(f.read())
time.sleep(4)
print("I hope you enjoyed The Story of the Little Cowbow")
time.sleep(60)
f = open("Line.txt", "r")
print("PS. if the story a bit childish is it's because it's a project is made with my cousin which is 4 years old")
exit()
